[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#15057E'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1764BD'

# Color used for almost all text
textColor = '#E6EBF7'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace | Homemade Apple)
# Default: "sans serif"
font = "Homemade Apple"